cors:
  origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  credentials: true

rateLimit:
  windowMs: 900000  # 15 minutes
  max: 1000         # Higher limit for development/testing
  standardHeaders: true
  legacyHeaders: false

headers:
  contentSecurityPolicy: true
  hsts:
    maxAge: 31536000
    includeSubDomains: true
    preload: true
